# Generated by Django 5.1.5 on 2025-01-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='paint',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
